export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
export const GET_IMAGES_FAILURE = 'GET_IMAGES_FAILURE'
export const GET_IMAGES_PENDING = 'GET_IMAGES_PENDING'
export const SET_CATEGORY = 'SET_CATEGORY'
